name: deepq-mkl
channels:
  - defaults
  - conda-forge
dependencies:
  - tensorflow=1.14.0=*mkl*
  - keras=2.3.1
  - gym
  - matplotlib
  - pandas
  - seaborn
  - h5py==2.10.0
  - pip
  - pip:
    - git+https://github.com/JLenssen/keras-rl
    - pymatching
